### ISSUE TITLE
Add short links for easy sharing

### ISSUE THREAD

**Issue by Marc-Winner** [dxinteractive/xenpaper#29]
Now the links are easily get big if the sequence is sufficiently large.
It is understood that links contain all the information about the sequence.
It is maybe so that there isn't sufficient storage to store all the instances. 
Maybe apply reversible compression if length of sequence exceeds some range?

**Comment by dxinteractive** [comment]
It's a nice idea, although a general purpose compression algorithm will likely not cut it here because the size of the charset used in the xenpaper grammar is not that many less than the size of the URLs charset. However it might be possible to shrink down often repeated sets characters, like "-" or "'." like how I believe GIF compression works. I am a bit doubtful how much shorter the URL can become.

May I ask why the URL length is a problem? https://www.typescriptlang.org/play for instance does the same thing but with typically much larger URLs, and all modern browsers can comfortably cope with 50K+ chars in the URL hash.

**Comment by dxinteractive** [comment]
The "real" way to do this would be to have a back end and a database that saves things. It's possible I might add something like that one day but xenpaper is intentionally just client-code only for now.

**Comment by Marc-Winner** [comment]
> It's a nice idea, but may I ask why the URL length is a problem? https://www.typescriptlang.org/play for instance does the same thing but with typically much larger URLs, and all modern browsers can comfortably cope with 50K+ chars in the URL hash.

I have a problem with typing code in messengers, e.g. Telegram cuts long text into pieces, making the link unusable. 

> The "real" way to do this would be to have a back end and a database that saves things. It's possible I might add something like that one day but xenpaper is intentionally just client-code only for now.

I expected something like this, just needed to check if there's possibility to do it. I will use short link services, no problem!
